version: 2
updates:
  - package-ecosystem: "npm" # See documentation for possible values
    directory: "/" # Location of package manifests
    schedule:
      interval: "daily"
    ignore:
      - dependency-name: "@types/node"
        update-types: ["version-update:semver-major"]
      - dependency-name: "p-queue"
        update-types: ["version-update:semver-major"]
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]
